# Site settings
title: Albert Gutierrez
email: albertgcsula@gmail.com
description: "Albert Gutierrez. Alberto Gutierrez. Web Development."
username: "albertgcsula"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
