# Site settings
title: Albert Gutierrez
email: albertgcsula@gmail.com
description: "Albert Gutierrez. Alberto Gutierrez. Web Development."
baseurl: ""
url: "http://albertgcsula.github.io"
username: "albertgcsula"

# Build settings
markdown: kramdown
permalink: pretty
